# Generated by Django 6.0.4 on 2026-04-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enquiry_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_form',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
