# Generated by Django 6.0.4 on 2026-04-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enquiry_form_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
