# Generated by Django 6.0.4 on 2026-04-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscribers_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('property_type', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=50)),
                ('bedrooms', models.CharField(max_length=50)),
                ('bathrooms', models.CharField(max_length=50)),
                ('appraisal_date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='enquiry_form',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='subscribers_form',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
