# Generated by Django 6.0.4 on 2026-04-20 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rental_form_alter_enquiry_form_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental_form',
            options={'verbose_name': 'Rental Appraisal', 'verbose_name_plural': 'Rental Appraisals'},
        ),
        migrations.AddField(
            model_name='rental_form',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Contact Status'),
        ),
        migrations.AddField(
            model_name='rental_form',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
