# Generated by Django 6.0.4 on 2026-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rental_form_options_rental_form_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental_form',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Rental Appraisal', 'verbose_name_plural': 'Rental Appraisals'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50),
            preserve_default=False,
        ),
    ]
