# Generated by Django 6.0.4 on 2026-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rental_form_options_remove_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_form',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('responded', 'Responded')], default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
