# Generated by Django 6.0.4 on 2026-04-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_enquiry_form_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry_form',
            old_name='date',
            new_name='sumbitted_by',
        ),
    ]
