# Generated by Django 6.0.4 on 2026-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_date_enquiry_form_sumbitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_form',
            name='sumbitted_by',
            field=models.DateField(auto_now_add=True),
        ),
    ]
