# Generated by Django 6.0.4 on 2026-04-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_enquiry_form_sumbitted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry_form',
            old_name='sumbitted_by',
            new_name='sumbitted_date',
        ),
    ]
