# Generated by Django 6.0.4 on 2026-04-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_sumbitted_by_enquiry_form_sumbitted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry_form',
            old_name='sumbitted_date',
            new_name='submitted_date',
        ),
    ]
