# Generated by Django 6.0.4 on 2026-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_sumbitted_date_enquiry_form_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_form',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('responded', 'Responded')], default='pending', max_length=50),
        ),
    ]
